sudo: required
language: ruby
matrix:
  include:
    - rvm: 2.0.0
    - rvm: 2.1.10
    - rvm: 2.2.6
    - rvm: 2.3.3
    - rvm: 2.4.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential cmake libpopt-dev libbz2-dev libruby ruby-dev
  - gem install bundler -v 1.12.5
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake compile
